---
  - hosts: all

    tasks:
      - name: Actualizar paquetes del sistema
        become: yes
        apt:
          update_cache: yes

      - name: Instalar nodejs-legacy
        become: yes
        apt:
          name: nodejs-legacy
          state: present

      - name: Instalar npm (Gestor de paquetes de node)
        become: yes
        apt:
          name: npm
          state: present

      - name: Clonar el repositorio
        become: yes
        git: repo=https://github.com/alberturria/Hospital dest=/opt/Hospital/ clone=yes force=yes

      - name: Actualizar node a la ultima versión
        become: yes
        command: sudo npm install -g n latest

      - name: Establecer versión estable
        become: yes
        command: sudo n stable
        
      - name: Instalar forever para poder lanzar la aplicación sin límites.
        npm: name=forever global=yes state=present


      - name: Copiar archivo de credenciales para conectar a la Base de Datos
        copy:
          src: /home/alberturria/Escritorio/IV/Hospital/clave.txt
          dest: /opt/Hospital/