---
  - hosts: all

    tasks:
      - name: Actualizar paquetes del sistema
        become: yes
        apt:
          update_cache: yes

      - name: Instalar npm (Gestor de paquetes de node)
        become: yes
        apt:
          name: npm
          state: present

      - name: Actualizar node a la ultima versión
        become: yes
        command: npm install -g n latest

      - name: Establecer versión estable
        become: yes
        command: n stable
        
      - name: Instalar forever para poder lanzar la aplicación sin límites.
        become: yes
        npm: name=forever global=yes state=present
